site_name: Documentation
site_url: https://example.com/
nav:
    - Login: index.md
    - Dashboard: dashboard.md
    - User Guide: about.md
extra_css: [extra.css]
theme: 
    name: material
    favicon: images/favicon.png
    logo: assets/eShikshya.png
    features: 
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
        - toc.integrate
        - search.suggest
        - search.highlight
        - content.tabs.link
        - content.code.annotation
        - content.code.copy
    language: en
    palette:
      - scheme: default
        toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to dark mode
      - scheme: slate
        toggle:
            icon: material/toggle-switch
            name: Switch to light mode


